FROM python:3.8-slim

RUN apt-get update && apt-get install -y \
    unzip \
    libffi-dev \
    libssl-dev \
    git \
    curl \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN pip install poetry


WORKDIR /app


COPY pyproject.toml poetry.lock /app/
COPY . /app


ENV POETRY_VIRTUALENVS_CREATE=false


RUN poetry install --no-interaction --no-ansi

# Entry point
ENTRYPOINT ["python", "sscollector.py"]
